# Generated by Django 4.1.2 on 2023-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_code', models.CharField(max_length=2, unique=True)),
                ('emoji_image', models.ImageField(null=True, upload_to='media/emoji/')),
            ],
        ),
    ]
