# Generated by Django 4.1.2 on 2023-01-17 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostReactions',
        ),
    ]
